import type { OrderValues, SheetId } from "./types";

export const SHEET_DEFAULTS: Record<SheetId, OrderValues> = {
  oltc: {
    frequency_hz: "50",
    phases: "III",
    regulation: "reversing",
    plus_minus: "8",
    oltc_tap_mid: "3",
    quantity: "1",
    mdu_model: "CMA7",
    standard: "IEC 60214",
    insulating_fluid: "mineral",
    nameplate_language: "en",
    tx_kind: "separated",
    capacity_mode: "constant",
    overload_mode: "iec",
    flux: "cfvv",
    tap_winding: "star_neutral",
    ust_mode: "constant",
    ins_fill: "catalog",
    potential_connection: "without",
    temp_sensor: "without",
    support_flange: "without",
    ambient_band: "-25~50",
    oltc_side: "hv",
  },
  octc: {
    frequency_hz: "50",
    phases: "III",
    quantity: "1",
    octc_drive: "handwheel",
    connection: "Y",
    octc_series: "IV",
    tx_kind: "separated",
  },
  dry: {
    family: "CZ",
    unit_count: "3",
    phases: "I",
    frequency_hz: "50",
    quantity: "1",
    mdu_model: "CMA7",
    dry_positions: "9",
    oltc_current_a: "500",
    oltc_um_kv: "40.5",
  },
  cma7: {
    frequency_hz: "50",
    quantity: "1",
    motor_voltage: "380_3",
    motor_network: "3acn",
    control_voltage: "220_ac",
    control_from: "motor",
    control_network: "2ac",
    control_protect: "without",
    heat_from: "motor",
    heat_network: "ac",
    heat_protect: "without",
    heater: "yes",
    heater_kind: "resistor",
    hand_lamp: "no",
    end_pos_sig: "without",
    crank_sig: "without",
    cam_s20: "without",
    incomplete_s21: "without",
    socket_x10: "without",
    bcd_qty: "without",
    ma_qty: "without",
    resistor_sig: "without",
    door_hinge: "left",
    bottom_plate: "holes50",
    padlock: "no",
    avr_model: "none",
    mdu_ip: "IP54",
  },
  "shm-d": {
    frequency_hz: "50",
    quantity: "1",
    shm_model: "SHM-D",
    motor_voltage: "220_240",
    control_from: "motor",
    heater: "yes",
    mdu_ip: "IP54",
  },
  hwv: {
    frequency_hz: "50",
    phases: "III",
    regulation: "reversing",
    plus_minus: "8",
    oltc_tap_mid: "3",
    quantity: "1",
    mdu_model: "CMA7",
    application: "power",
    tx_kind: "separated",
    capacity_mode: "constant",
    overload_mode: "iec",
    flux: "cfvv",
    tap_winding: "star_neutral",
    range_shape: "symmetric",
    ust_mode: "constant",
    potential_connection: "without",
    paint: "RAL7040",
    nameplate_language: "en",
    ambient_temp: "-25~+40",
  },
};
