import type { OrderValues, SheetId } from "./types";

export const SHEET_DEFAULTS: Record<SheetId, OrderValues> = {
  oltc: {
    frequency_hz: "50",
    phases: "III",
    regulation: "reversing",
    plus_minus: "8",
    oltc_tap_mid: "3",
    quantity: "1",
    mdu_model: "CMA7",
    standard: "IEC 60214",
    insulating_fluid: "mineral",
    nameplate_language: "en",
    designer_phone_cc: "+86",
  },
  octc: {
    frequency_hz: "50",
    phases: "III",
    quantity: "1",
    octc_drive: "handwheel",
    connection: "Y",
    octc_series: "IV",
    designer_phone_cc: "+86",
  },
  dry: {
    family: "CZ",
    unit_count: "3",
    phases: "I",
    frequency_hz: "50",
    quantity: "1",
    mdu_model: "CMA7",
    dry_positions: "9",
    oltc_current_a: "500",
    oltc_um_kv: "40.5",
    designer_phone_cc: "+86",
  },
  cma7: {
    frequency_hz: "50",
    quantity: "1",
    motor_voltage: "380_3",
    control_voltage: "220_ac",
    heater: "yes",
    mdu_ip: "IP54",
    designer_phone_cc: "+86",
  },
  "shm-d": {
    frequency_hz: "50",
    quantity: "1",
    shm_model: "SHM-D",
    heater: "yes",
    mdu_ip: "IP54",
    designer_phone_cc: "+86",
  },
  hwv: {
    frequency_hz: "50",
    phases: "III",
    regulation: "reversing",
    plus_minus: "8",
    oltc_tap_mid: "3",
    quantity: "1",
    mdu_model: "CMA7",
    application: "power",
    tx_kind: "separated",
    capacity_mode: "constant",
    overload_mode: "iec",
    flux: "cfvv",
    tap_winding: "star_neutral",
    range_shape: "symmetric",
    ust_mode: "constant",
    potential_connection: "without",
    paint: "RAL7040",
    nameplate_language: "en",
    ambient_temp: "-25~+40",
    designer_phone_cc: "+86",
  },
};
